# Generated by Django 4.1.7 on 2023-04-08 21:53

import cookbook.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_prometheus.models


class Migration(migrations.Migration):
    dependencies = [
        ("cookbook", "0188_space_no_sharing_limit"),
    ]

    operations = [
        migrations.CreateModel(
            name="Utensil",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=128,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                (
                    "plural_name",
                    models.CharField(
                        blank=True, default=None, max_length=128, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cookbook.space"
                    ),
                ),
            ],
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("equipment"),
                models.Model,
                cookbook.models.PermissionModelMixin,
            ),
        ),
        migrations.CreateModel(
            name="StepUtensil",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("no_amount", models.BooleanField(default=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=16, default=0, max_digits=32),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "utensil",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cookbook.utensil",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "pk"],
            },
            bases=(
                django_prometheus.models.ExportModelOperationsMixin("step_utensil"),
                models.Model,
                cookbook.models.PermissionModelMixin,
            ),
        ),
        migrations.AddField(
            model_name="step",
            name="utensils",
            field=models.ManyToManyField(blank=True, to="cookbook.steputensil"),
        ),
        migrations.AddIndex(
            model_name="steputensil",
            index=models.Index(fields=["id"], name="cookbook_st_id_68d800_idx"),
        ),
    ]
